// ═══ CONFIGURACIÓN PEER REVIEW ═══

export const REVIEW_CONFIG = {
  MIN_GRADO_REVIEWER: 8,
  MIN_PUBLICACIONES_REVIEWER: 2,
  REVIEWERS_POR_PUBLICACION: 2,
  PLAZO_REVIEW_DIAS: 5,
  XP_POR_REVIEW: 5,
};
